[package]
name = "gitignore-cli"
version = "0.1.0"
authors = ["Milan <milanlandaverde@gmail.com>"]
edition = "2018"

[[bin]]
name = "gitignore"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33.3"
